import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const switchTheme = async (theme: "fire" | "water" | "grass" | null) => {
    const switchThemeUrl = new URL(
      "/api/switch-theme",
      window.location.toString()
    );
    switchThemeUrl.searchParams.set("theme", theme);
    await fetch(switchThemeUrl);
    // the response will set a "theme" cookie
    // now we refresh to trigger our edge middleware
    window.location.reload();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          It's dangerous to go alone! Pick your theme.
        </p>

        <div className={styles.grid}>
          <a
            onClick={() => {
              switchTheme("fire");
            }}
            className={styles.card + " " + styles.fire}
          >
            <h2>Fire</h2>
            <p>It's a hot topic</p>
          </a>

          <a
            onClick={() => {
              switchTheme("water");
            }}
            className={styles.card + " " + styles.water}
          >
            <h2>Water</h2>
            <p>Stay hydrated homies</p>
          </a>

          <a
            onClick={() => {
              switchTheme("grass");
            }}
            className={styles.card + " " + styles.grass}
          >
            <h2>Grass</h2>
            <p>I love dollars</p>
          </a>

          <a
            onClick={() => {
              switchTheme(null);
            }}
            className={styles.card}
          >
            <h2>Reset</h2>
            <p>I really want to go alone</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
